################################################################
#
# Static configuration for Traefik v2.
#
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

api:
  insecure: false
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: dwp-proxy
    exposedByDefault: false
  file:
    filename: /etc/traefik/ssl.yml
    watch: true
